### ISSUE TITLE
Is this repository necessary for the SMS tool?

### ISSUE THREAD

**Issue by jungshadow** [votinginfoproject/sms-infrastructure#2]
Looking at the [sms-compose](https://github.com/votinginfoproject/sms-compose) repository, I'm curious if this repository is still used. If so, it might be worth mentioning in the [sms-compose README](https://github.com/votinginfoproject/sms-compose/blob/master/README.md). If not, it may be worth noting that this repository is no longer used or that it's marked for deletion. Otherwise, this may be confusing for developers looking to use the code. Thanks!

**Comment by tie-rack** [comment]
Good point. This repository is no longer used for development or deployment. I'll add a prominent note to this repo's README for now.

**Comment by jungshadow** [comment]
Excellent! Thanks, @tie-rack!
